<?php

namespace SiteBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function home()
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	     ->orderBy('a.date', 'DESC')
	     ->setMaxResults(5)
	  	;

	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	}
}
